#include "RHIVkTypeConversion.h"

namespace rhi::vulkan {

namespace {

// RHIImageLayout <-> VkImageLayout mapping using Map
const Map<RHIImageLayout, VkImageLayout> gk_rhiToVkImageLayout = {
    {RHIImageLayout::Undefined, VK_IMAGE_LAYOUT_UNDEFINED},
    {RHIImageLayout::General, VK_IMAGE_LAYOUT_GENERAL},
    {RHIImageLayout::ColorAttachment, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL},
    {RHIImageLayout::DepthStencilAttachment, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL},
    {RHIImageLayout::DepthStencilReadOnly, VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL},
    {RHIImageLayout::ShaderReadOnly, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},
    {RHIImageLayout::TransferSrc, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL},
    {RHIImageLayout::TransferDst, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL},
    {RHIImageLayout::Preinitialized, VK_IMAGE_LAYOUT_PREINITIALIZED},
    {RHIImageLayout::DepthReadOnlyStencilAttachment, VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL},
    {RHIImageLayout::DepthAttachmentStencilReadOnly, VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL},
    {RHIImageLayout::DepthAttachment, VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL},
    {RHIImageLayout::DepthReadOnly, VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL},
    {RHIImageLayout::StencilAttachment, VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL},
    {RHIImageLayout::StencilReadOnly, VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL},
    {RHIImageLayout::ReadOnly, VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL},
    {RHIImageLayout::Attachment, VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL},
    {RHIImageLayout::Present, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR},
    {RHIImageLayout::SharedPresent, VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR},
    {RHIImageLayout::FragmentDensityMap, VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT},
    {RHIImageLayout::FragmentShadingRateAttachment, VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR},
    {RHIImageLayout::AttachmentFeedbackLoop, VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT},
};

// RHIDescriptorType <-> VkDescriptorType mapping
const Map<RHIDescriptorType, VkDescriptorType> gk_rhiToVkDescriptorType = {
    {RHIDescriptorType::UniformBuffer, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER},
    {RHIDescriptorType::StorageBuffer, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER},
    {RHIDescriptorType::SampledImage, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE},
    {RHIDescriptorType::StorageImage, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE},
    {RHIDescriptorType::Sampler, VK_DESCRIPTOR_TYPE_SAMPLER},
    {RHIDescriptorType::CombinedImageSampler, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER},
};

Map<VkDescriptorType, RHIDescriptorType> createVkToRhiDescriptorTypeMap() {
    Map<VkDescriptorType, RHIDescriptorType> map;
    for (const auto& pair : gk_rhiToVkDescriptorType) {
        map[pair.second] = pair.first;
    }
    return map;
}

Map<VkImageLayout, RHIImageLayout> createVkToRhiImageLayoutMap() {
    Map<VkImageLayout, RHIImageLayout> map;
    for (const auto& pair : gk_rhiToVkImageLayout) {
        map[pair.second] = pair.first;
    }
    return map;
}
const Map<VkImageLayout, RHIImageLayout> gk_vkToRhiImageLayout = createVkToRhiImageLayoutMap();

const Map<RHIFormat, VkFormat> gk_rhiToVkFormat = {
    {RHIFormat::RHI_FORMAT_UNDEFINED, VK_FORMAT_UNDEFINED},
    {RHIFormat::RHI_FORMAT_R4G4_UNORM_PACK8, VK_FORMAT_R4G4_UNORM_PACK8},
    {RHIFormat::RHI_FORMAT_R4G4B4A4_UNORM_PACK16, VK_FORMAT_R4G4B4A4_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_B4G4R4A4_UNORM_PACK16, VK_FORMAT_B4G4R4A4_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_R5G6B5_UNORM_PACK16, VK_FORMAT_R5G6B5_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_B5G6R5_UNORM_PACK16, VK_FORMAT_B5G6R5_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_R5G5B5A1_UNORM_PACK16, VK_FORMAT_R5G5B5A1_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_B5G5R5A1_UNORM_PACK16, VK_FORMAT_B5G5R5A1_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_A1R5G5B5_UNORM_PACK16, VK_FORMAT_A1R5G5B5_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_R8_UNORM, VK_FORMAT_R8_UNORM},
    {RHIFormat::RHI_FORMAT_R8_SNORM, VK_FORMAT_R8_SNORM},
    {RHIFormat::RHI_FORMAT_R8_USCALED, VK_FORMAT_R8_USCALED},
    {RHIFormat::RHI_FORMAT_R8_SSCALED, VK_FORMAT_R8_SSCALED},
    {RHIFormat::RHI_FORMAT_R8_UINT, VK_FORMAT_R8_UINT},
    {RHIFormat::RHI_FORMAT_R8_SINT, VK_FORMAT_R8_SINT},
    {RHIFormat::RHI_FORMAT_R8_SRGB, VK_FORMAT_R8_SRGB},
    {RHIFormat::RHI_FORMAT_R8G8_UNORM, VK_FORMAT_R8G8_UNORM},
    {RHIFormat::RHI_FORMAT_R8G8_SNORM, VK_FORMAT_R8G8_SNORM},
    {RHIFormat::RHI_FORMAT_R8G8_USCALED, VK_FORMAT_R8G8_USCALED},
    {RHIFormat::RHI_FORMAT_R8G8_SSCALED, VK_FORMAT_R8G8_SSCALED},
    {RHIFormat::RHI_FORMAT_R8G8_UINT, VK_FORMAT_R8G8_UINT},
    {RHIFormat::RHI_FORMAT_R8G8_SINT, VK_FORMAT_R8G8_SINT},
    {RHIFormat::RHI_FORMAT_R8G8_SRGB, VK_FORMAT_R8G8_SRGB},
    {RHIFormat::RHI_FORMAT_R8G8B8_UNORM, VK_FORMAT_R8G8B8_UNORM},
    {RHIFormat::RHI_FORMAT_R8G8B8_SNORM, VK_FORMAT_R8G8B8_SNORM},
    {RHIFormat::RHI_FORMAT_R8G8B8_USCALED, VK_FORMAT_R8G8B8_USCALED},
    {RHIFormat::RHI_FORMAT_R8G8B8_SSCALED, VK_FORMAT_R8G8B8_SSCALED},
    {RHIFormat::RHI_FORMAT_R8G8B8_UINT, VK_FORMAT_R8G8B8_UINT},
    {RHIFormat::RHI_FORMAT_R8G8B8_SINT, VK_FORMAT_R8G8B8_SINT},
    {RHIFormat::RHI_FORMAT_R8G8B8_SRGB, VK_FORMAT_R8G8B8_SRGB},
    {RHIFormat::RHI_FORMAT_B8G8R8_UNORM, VK_FORMAT_B8G8R8_UNORM},
    {RHIFormat::RHI_FORMAT_B8G8R8_SNORM, VK_FORMAT_B8G8R8_SNORM},
    {RHIFormat::RHI_FORMAT_B8G8R8_USCALED, VK_FORMAT_B8G8R8_USCALED},
    {RHIFormat::RHI_FORMAT_B8G8R8_SSCALED, VK_FORMAT_B8G8R8_SSCALED},
    {RHIFormat::RHI_FORMAT_B8G8R8_UINT, VK_FORMAT_B8G8R8_UINT},
    {RHIFormat::RHI_FORMAT_B8G8R8_SINT, VK_FORMAT_B8G8R8_SINT},
    {RHIFormat::RHI_FORMAT_B8G8R8_SRGB, VK_FORMAT_B8G8R8_SRGB},
    {RHIFormat::RHI_FORMAT_R8G8B8A8_UNORM, VK_FORMAT_R8G8B8A8_UNORM},
    {RHIFormat::RHI_FORMAT_R8G8B8A8_SNORM, VK_FORMAT_R8G8B8A8_SNORM},
    {RHIFormat::RHI_FORMAT_R8G8B8A8_USCALED, VK_FORMAT_R8G8B8A8_USCALED},
    {RHIFormat::RHI_FORMAT_R8G8B8A8_SSCALED, VK_FORMAT_R8G8B8A8_SSCALED},
    {RHIFormat::RHI_FORMAT_R8G8B8A8_UINT, VK_FORMAT_R8G8B8A8_UINT},
    {RHIFormat::RHI_FORMAT_R8G8B8A8_SINT, VK_FORMAT_R8G8B8A8_SINT},
    {RHIFormat::RHI_FORMAT_R8G8B8A8_SRGB, VK_FORMAT_R8G8B8A8_SRGB},
    {RHIFormat::RHI_FORMAT_B8G8R8A8_UNORM, VK_FORMAT_B8G8R8A8_UNORM},
    {RHIFormat::RHI_FORMAT_B8G8R8A8_SNORM, VK_FORMAT_B8G8R8A8_SNORM},
    {RHIFormat::RHI_FORMAT_B8G8R8A8_USCALED, VK_FORMAT_B8G8R8A8_USCALED},
    {RHIFormat::RHI_FORMAT_B8G8R8A8_SSCALED, VK_FORMAT_B8G8R8A8_SSCALED},
    {RHIFormat::RHI_FORMAT_B8G8R8A8_UINT, VK_FORMAT_B8G8R8A8_UINT},
    {RHIFormat::RHI_FORMAT_B8G8R8A8_SINT, VK_FORMAT_B8G8R8A8_SINT},
    {RHIFormat::RHI_FORMAT_B8G8R8A8_SRGB, VK_FORMAT_B8G8R8A8_SRGB},
    {RHIFormat::RHI_FORMAT_A8B8G8R8_UNORM_PACK32, VK_FORMAT_A8B8G8R8_UNORM_PACK32},
    {RHIFormat::RHI_FORMAT_A8B8G8R8_SNORM_PACK32, VK_FORMAT_A8B8G8R8_SNORM_PACK32},
    {RHIFormat::RHI_FORMAT_A8B8G8R8_USCALED_PACK32, VK_FORMAT_A8B8G8R8_USCALED_PACK32},
    {RHIFormat::RHI_FORMAT_A8B8G8R8_SSCALED_PACK32, VK_FORMAT_A8B8G8R8_SSCALED_PACK32},
    {RHIFormat::RHI_FORMAT_A8B8G8R8_UINT_PACK32, VK_FORMAT_A8B8G8R8_UINT_PACK32},
    {RHIFormat::RHI_FORMAT_A8B8G8R8_SINT_PACK32, VK_FORMAT_A8B8G8R8_SINT_PACK32},
    {RHIFormat::RHI_FORMAT_A8B8G8R8_SRGB_PACK32, VK_FORMAT_A8B8G8R8_SRGB_PACK32},
    {RHIFormat::RHI_FORMAT_A2R10G10B10_UNORM_PACK32, VK_FORMAT_A2R10G10B10_UNORM_PACK32},
    {RHIFormat::RHI_FORMAT_A2R10G10B10_SNORM_PACK32, VK_FORMAT_A2R10G10B10_SNORM_PACK32},
    {RHIFormat::RHI_FORMAT_A2R10G10B10_USCALED_PACK32, VK_FORMAT_A2R10G10B10_USCALED_PACK32},
    {RHIFormat::RHI_FORMAT_A2R10G10B10_SSCALED_PACK32, VK_FORMAT_A2R10G10B10_SSCALED_PACK32},
    {RHIFormat::RHI_FORMAT_A2R10G10B10_UINT_PACK32, VK_FORMAT_A2R10G10B10_UINT_PACK32},
    {RHIFormat::RHI_FORMAT_A2R10G10B10_SINT_PACK32, VK_FORMAT_A2R10G10B10_SINT_PACK32},
    {RHIFormat::RHI_FORMAT_A2B10G10R10_UNORM_PACK32, VK_FORMAT_A2B10G10R10_UNORM_PACK32},
    {RHIFormat::RHI_FORMAT_A2B10G10R10_SNORM_PACK32, VK_FORMAT_A2B10G10R10_SNORM_PACK32},
    {RHIFormat::RHI_FORMAT_A2B10G10R10_USCALED_PACK32, VK_FORMAT_A2B10G10R10_USCALED_PACK32},
    {RHIFormat::RHI_FORMAT_A2B10G10R10_SSCALED_PACK32, VK_FORMAT_A2B10G10R10_SSCALED_PACK32},
    {RHIFormat::RHI_FORMAT_A2B10G10R10_UINT_PACK32, VK_FORMAT_A2B10G10R10_UINT_PACK32},
    {RHIFormat::RHI_FORMAT_A2B10G10R10_SINT_PACK32, VK_FORMAT_A2B10G10R10_SINT_PACK32},
    {RHIFormat::RHI_FORMAT_R16_UNORM, VK_FORMAT_R16_UNORM},
    {RHIFormat::RHI_FORMAT_R16_SNORM, VK_FORMAT_R16_SNORM},
    {RHIFormat::RHI_FORMAT_R16_USCALED, VK_FORMAT_R16_USCALED},
    {RHIFormat::RHI_FORMAT_R16_SSCALED, VK_FORMAT_R16_SSCALED},
    {RHIFormat::RHI_FORMAT_R16_UINT, VK_FORMAT_R16_UINT},
    {RHIFormat::RHI_FORMAT_R16_SINT, VK_FORMAT_R16_SINT},
    {RHIFormat::RHI_FORMAT_R16_SFLOAT, VK_FORMAT_R16_SFLOAT},
    {RHIFormat::RHI_FORMAT_R16G16_UNORM, VK_FORMAT_R16G16_UNORM},
    {RHIFormat::RHI_FORMAT_R16G16_SNORM, VK_FORMAT_R16G16_SNORM},
    {RHIFormat::RHI_FORMAT_R16G16_USCALED, VK_FORMAT_R16G16_USCALED},
    {RHIFormat::RHI_FORMAT_R16G16_SSCALED, VK_FORMAT_R16G16_SSCALED},
    {RHIFormat::RHI_FORMAT_R16G16_UINT, VK_FORMAT_R16G16_UINT},
    {RHIFormat::RHI_FORMAT_R16G16_SINT, VK_FORMAT_R16G16_SINT},
    {RHIFormat::RHI_FORMAT_R16G16_SFLOAT, VK_FORMAT_R16G16_SFLOAT},
    {RHIFormat::RHI_FORMAT_R16G16B16_UNORM, VK_FORMAT_R16G16B16_UNORM},
    {RHIFormat::RHI_FORMAT_R16G16B16_SNORM, VK_FORMAT_R16G16B16_SNORM},
    {RHIFormat::RHI_FORMAT_R16G16B16_USCALED, VK_FORMAT_R16G16B16_USCALED},
    {RHIFormat::RHI_FORMAT_R16G16B16_SSCALED, VK_FORMAT_R16G16B16_SSCALED},
    {RHIFormat::RHI_FORMAT_R16G16B16_UINT, VK_FORMAT_R16G16B16_UINT},
    {RHIFormat::RHI_FORMAT_R16G16B16_SINT, VK_FORMAT_R16G16B16_SINT},
    {RHIFormat::RHI_FORMAT_R16G16B16_SFLOAT, VK_FORMAT_R16G16B16_SFLOAT},
    {RHIFormat::RHI_FORMAT_R16G16B16A16_UNORM, VK_FORMAT_R16G16B16A16_UNORM},
    {RHIFormat::RHI_FORMAT_R16G16B16A16_SNORM, VK_FORMAT_R16G16B16A16_SNORM},
    {RHIFormat::RHI_FORMAT_R16G16B16A16_USCALED, VK_FORMAT_R16G16B16A16_USCALED},
    {RHIFormat::RHI_FORMAT_R16G16B16A16_SSCALED, VK_FORMAT_R16G16B16A16_SSCALED},
    {RHIFormat::RHI_FORMAT_R16G16B16A16_UINT, VK_FORMAT_R16G16B16A16_UINT},
    {RHIFormat::RHI_FORMAT_R16G16B16A16_SINT, VK_FORMAT_R16G16B16A16_SINT},
    {RHIFormat::RHI_FORMAT_R16G16B16A16_SFLOAT, VK_FORMAT_R16G16B16A16_SFLOAT},
    {RHIFormat::RHI_FORMAT_R32_UINT, VK_FORMAT_R32_UINT},
    {RHIFormat::RHI_FORMAT_R32_SINT, VK_FORMAT_R32_SINT},
    {RHIFormat::RHI_FORMAT_R32_SFLOAT, VK_FORMAT_R32_SFLOAT},
    {RHIFormat::RHI_FORMAT_R32G32_UINT, VK_FORMAT_R32G32_UINT},
    {RHIFormat::RHI_FORMAT_R32G32_SINT, VK_FORMAT_R32G32_SINT},
    {RHIFormat::RHI_FORMAT_R32G32_SFLOAT, VK_FORMAT_R32G32_SFLOAT},
    {RHIFormat::RHI_FORMAT_R32G32B32_UINT, VK_FORMAT_R32G32B32_UINT},
    {RHIFormat::RHI_FORMAT_R32G32B32_SINT, VK_FORMAT_R32G32B32_SINT},
    {RHIFormat::RHI_FORMAT_R32G32B32_SFLOAT, VK_FORMAT_R32G32B32_SFLOAT},
    {RHIFormat::RHI_FORMAT_R32G32B32A32_UINT, VK_FORMAT_R32G32B32A32_UINT},
    {RHIFormat::RHI_FORMAT_R32G32B32A32_SINT, VK_FORMAT_R32G32B32A32_SINT},
    {RHIFormat::RHI_FORMAT_R32G32B32A32_SFLOAT, VK_FORMAT_R32G32B32A32_SFLOAT},
    {RHIFormat::RHI_FORMAT_R64_UINT, VK_FORMAT_R64_UINT},
    {RHIFormat::RHI_FORMAT_R64_SINT, VK_FORMAT_R64_SINT},
    {RHIFormat::RHI_FORMAT_R64_SFLOAT, VK_FORMAT_R64_SFLOAT},
    {RHIFormat::RHI_FORMAT_R64G64_UINT, VK_FORMAT_R64G64_UINT},
    {RHIFormat::RHI_FORMAT_R64G64_SINT, VK_FORMAT_R64G64_SINT},
    {RHIFormat::RHI_FORMAT_R64G64_SFLOAT, VK_FORMAT_R64G64_SFLOAT},
    {RHIFormat::RHI_FORMAT_R64G64B64_UINT, VK_FORMAT_R64G64B64_UINT},
    {RHIFormat::RHI_FORMAT_R64G64B64_SINT, VK_FORMAT_R64G64B64_SINT},
    {RHIFormat::RHI_FORMAT_R64G64B64_SFLOAT, VK_FORMAT_R64G64B64_SFLOAT},
    {RHIFormat::RHI_FORMAT_R64G64B64A64_UINT, VK_FORMAT_R64G64B64A64_UINT},
    {RHIFormat::RHI_FORMAT_R64G64B64A64_SINT, VK_FORMAT_R64G64B64A64_SINT},
    {RHIFormat::RHI_FORMAT_R64G64B64A64_SFLOAT, VK_FORMAT_R64G64B64A64_SFLOAT},
    {RHIFormat::RHI_FORMAT_B10G11R11_UFLOAT_PACK32, VK_FORMAT_B10G11R11_UFLOAT_PACK32},
    {RHIFormat::RHI_FORMAT_E5B9G9R9_UFLOAT_PACK32, VK_FORMAT_E5B9G9R9_UFLOAT_PACK32},
    {RHIFormat::RHI_FORMAT_D16_UNORM, VK_FORMAT_D16_UNORM},
    {RHIFormat::RHI_FORMAT_X8_D24_UNORM_PACK32, VK_FORMAT_X8_D24_UNORM_PACK32},
    {RHIFormat::RHI_FORMAT_D32_SFLOAT, VK_FORMAT_D32_SFLOAT},
    {RHIFormat::RHI_FORMAT_S8_UINT, VK_FORMAT_S8_UINT},
    {RHIFormat::RHI_FORMAT_D16_UNORM_S8_UINT, VK_FORMAT_D16_UNORM_S8_UINT},
    {RHIFormat::RHI_FORMAT_D24_UNORM_S8_UINT, VK_FORMAT_D24_UNORM_S8_UINT},
    {RHIFormat::RHI_FORMAT_D32_SFLOAT_S8_UINT, VK_FORMAT_D32_SFLOAT_S8_UINT},
    {RHIFormat::RHI_FORMAT_BC1_RGB_UNORM_BLOCK, VK_FORMAT_BC1_RGB_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_BC1_RGB_SRGB_BLOCK, VK_FORMAT_BC1_RGB_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_BC1_RGBA_UNORM_BLOCK, VK_FORMAT_BC1_RGBA_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_BC1_RGBA_SRGB_BLOCK, VK_FORMAT_BC1_RGBA_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_BC2_UNORM_BLOCK, VK_FORMAT_BC2_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_BC2_SRGB_BLOCK, VK_FORMAT_BC2_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_BC3_UNORM_BLOCK, VK_FORMAT_BC3_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_BC3_SRGB_BLOCK, VK_FORMAT_BC3_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_BC4_UNORM_BLOCK, VK_FORMAT_BC4_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_BC4_SNORM_BLOCK, VK_FORMAT_BC4_SNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_BC5_UNORM_BLOCK, VK_FORMAT_BC5_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_BC5_SNORM_BLOCK, VK_FORMAT_BC5_SNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_BC6H_UFLOAT_BLOCK, VK_FORMAT_BC6H_UFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_BC6H_SFLOAT_BLOCK, VK_FORMAT_BC6H_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_BC7_UNORM_BLOCK, VK_FORMAT_BC7_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_BC7_SRGB_BLOCK, VK_FORMAT_BC7_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ETC2_R8G8B8_UNORM_BLOCK, VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ETC2_R8G8B8_SRGB_BLOCK, VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK, VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK, VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK, VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK, VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_EAC_R11_UNORM_BLOCK, VK_FORMAT_EAC_R11_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_EAC_R11_SNORM_BLOCK, VK_FORMAT_EAC_R11_SNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_EAC_R11G11_UNORM_BLOCK, VK_FORMAT_EAC_R11G11_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_EAC_R11G11_SNORM_BLOCK, VK_FORMAT_EAC_R11G11_SNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_4x4_UNORM_BLOCK, VK_FORMAT_ASTC_4x4_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_4x4_SRGB_BLOCK, VK_FORMAT_ASTC_4x4_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_5x4_UNORM_BLOCK, VK_FORMAT_ASTC_5x4_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_5x4_SRGB_BLOCK, VK_FORMAT_ASTC_5x4_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_5x5_UNORM_BLOCK, VK_FORMAT_ASTC_5x5_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_5x5_SRGB_BLOCK, VK_FORMAT_ASTC_5x5_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_6x5_UNORM_BLOCK, VK_FORMAT_ASTC_6x5_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_6x5_SRGB_BLOCK, VK_FORMAT_ASTC_6x5_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_6x6_UNORM_BLOCK, VK_FORMAT_ASTC_6x6_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_6x6_SRGB_BLOCK, VK_FORMAT_ASTC_6x6_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_8x5_UNORM_BLOCK, VK_FORMAT_ASTC_8x5_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_8x5_SRGB_BLOCK, VK_FORMAT_ASTC_8x5_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_8x6_UNORM_BLOCK, VK_FORMAT_ASTC_8x6_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_8x6_SRGB_BLOCK, VK_FORMAT_ASTC_8x6_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_8x8_UNORM_BLOCK, VK_FORMAT_ASTC_8x8_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_8x8_SRGB_BLOCK, VK_FORMAT_ASTC_8x8_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x5_UNORM_BLOCK, VK_FORMAT_ASTC_10x5_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x5_SRGB_BLOCK, VK_FORMAT_ASTC_10x5_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x6_UNORM_BLOCK, VK_FORMAT_ASTC_10x6_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x6_SRGB_BLOCK, VK_FORMAT_ASTC_10x6_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x8_UNORM_BLOCK, VK_FORMAT_ASTC_10x8_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x8_SRGB_BLOCK, VK_FORMAT_ASTC_10x8_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x10_UNORM_BLOCK, VK_FORMAT_ASTC_10x10_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x10_SRGB_BLOCK, VK_FORMAT_ASTC_10x10_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_12x10_UNORM_BLOCK, VK_FORMAT_ASTC_12x10_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_12x10_SRGB_BLOCK, VK_FORMAT_ASTC_12x10_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_12x12_UNORM_BLOCK, VK_FORMAT_ASTC_12x12_UNORM_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_12x12_SRGB_BLOCK, VK_FORMAT_ASTC_12x12_SRGB_BLOCK},
    {RHIFormat::RHI_FORMAT_G8B8G8R8_422_UNORM, VK_FORMAT_G8B8G8R8_422_UNORM},
    {RHIFormat::RHI_FORMAT_B8G8R8G8_422_UNORM, VK_FORMAT_B8G8R8G8_422_UNORM},
    {RHIFormat::RHI_FORMAT_G8_B8_R8_3PLANE_420_UNORM, VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM},
    {RHIFormat::RHI_FORMAT_G8_B8R8_2PLANE_420_UNORM, VK_FORMAT_G8_B8R8_2PLANE_420_UNORM},
    {RHIFormat::RHI_FORMAT_G8_B8_R8_3PLANE_422_UNORM, VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM},
    {RHIFormat::RHI_FORMAT_G8_B8R8_2PLANE_422_UNORM, VK_FORMAT_G8_B8R8_2PLANE_422_UNORM},
    {RHIFormat::RHI_FORMAT_G8_B8_R8_3PLANE_444_UNORM, VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM},
    {RHIFormat::RHI_FORMAT_R10X6_UNORM_PACK16, VK_FORMAT_R10X6_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_R10X6G10X6_UNORM_2PACK16, VK_FORMAT_R10X6G10X6_UNORM_2PACK16},
    {RHIFormat::RHI_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16, VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16},
    {RHIFormat::RHI_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16, VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16},
    {RHIFormat::RHI_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16, VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16},
    {RHIFormat::RHI_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16, VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16, VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16, VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16, VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16, VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_R12X4_UNORM_PACK16, VK_FORMAT_R12X4_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_R12X4G12X4_UNORM_2PACK16, VK_FORMAT_R12X4G12X4_UNORM_2PACK16},
    {RHIFormat::RHI_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16, VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16},
    {RHIFormat::RHI_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16, VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16},
    {RHIFormat::RHI_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16, VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16},
    {RHIFormat::RHI_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16, VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16, VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16, VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16, VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16, VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G16B16G16R16_422_UNORM, VK_FORMAT_G16B16G16R16_422_UNORM},
    {RHIFormat::RHI_FORMAT_B16G16R16G16_422_UNORM, VK_FORMAT_B16G16R16G16_422_UNORM},
    {RHIFormat::RHI_FORMAT_G16_B16_R16_3PLANE_420_UNORM, VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM},
    {RHIFormat::RHI_FORMAT_G16_B16R16_2PLANE_420_UNORM, VK_FORMAT_G16_B16R16_2PLANE_420_UNORM},
    {RHIFormat::RHI_FORMAT_G16_B16_R16_3PLANE_422_UNORM, VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM},
    {RHIFormat::RHI_FORMAT_G16_B16R16_2PLANE_422_UNORM, VK_FORMAT_G16_B16R16_2PLANE_422_UNORM},
    {RHIFormat::RHI_FORMAT_G16_B16_R16_3PLANE_444_UNORM, VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM},
    {RHIFormat::RHI_FORMAT_G8_B8R8_2PLANE_444_UNORM, VK_FORMAT_G8_B8R8_2PLANE_444_UNORM},
    {RHIFormat::RHI_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16, VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16, VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16},
    {RHIFormat::RHI_FORMAT_G16_B16R16_2PLANE_444_UNORM, VK_FORMAT_G16_B16R16_2PLANE_444_UNORM},
    {RHIFormat::RHI_FORMAT_A4R4G4B4_UNORM_PACK16, VK_FORMAT_A4R4G4B4_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_A4B4G4R4_UNORM_PACK16, VK_FORMAT_A4B4G4R4_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_ASTC_4x4_SFLOAT_BLOCK, VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_5x4_SFLOAT_BLOCK, VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_5x5_SFLOAT_BLOCK, VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_6x5_SFLOAT_BLOCK, VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_6x6_SFLOAT_BLOCK, VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_8x5_SFLOAT_BLOCK, VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_8x6_SFLOAT_BLOCK, VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_8x8_SFLOAT_BLOCK, VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x5_SFLOAT_BLOCK, VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x6_SFLOAT_BLOCK, VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x8_SFLOAT_BLOCK, VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_10x10_SFLOAT_BLOCK, VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_12x10_SFLOAT_BLOCK, VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_ASTC_12x12_SFLOAT_BLOCK, VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK},
    {RHIFormat::RHI_FORMAT_A1B5G5R5_UNORM_PACK16, VK_FORMAT_A1B5G5R5_UNORM_PACK16},
    {RHIFormat::RHI_FORMAT_A8_UNORM, VK_FORMAT_A8_UNORM},
    {RHIFormat::RHI_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG, VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG},
    {RHIFormat::RHI_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG, VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG},
    {RHIFormat::RHI_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG, VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG},
    {RHIFormat::RHI_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG, VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG},
    {RHIFormat::RHI_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG, VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG},
    {RHIFormat::RHI_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG, VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG},
    {RHIFormat::RHI_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG, VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG},
    {RHIFormat::RHI_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG, VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG},
    {RHIFormat::RHI_FORMAT_R16G16_SFIXED5_NV, VK_FORMAT_R16G16_SFIXED5_NV}
};

Map<VkFormat, RHIFormat> createVkToRhiFormatMap()
{
    Map<VkFormat, RHIFormat> map;
    for (const auto& pair : gk_rhiToVkFormat) {
        map[pair.second] = pair.first;
    }
    return map;
}

const Map<VkFormat, RHIFormat> gk_vkToRhiFormat = createVkToRhiFormatMap();

const Map<RHIColorSpace, VkColorSpaceKHR> gk_colorSpaceMap = {
    {RHIColorSpace::RHI_COLOR_SPACE_SRGB_NONLINEAR_KHR, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR},
    {RHIColorSpace::RHI_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT, VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT, VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT, VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_DCI_P3_NONLINEAR_EXT, VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_BT709_LINEAR_EXT, VK_COLOR_SPACE_BT709_LINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_BT709_NONLINEAR_EXT, VK_COLOR_SPACE_BT709_NONLINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_BT2020_LINEAR_EXT, VK_COLOR_SPACE_BT2020_LINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_HDR10_ST2084_EXT, VK_COLOR_SPACE_HDR10_ST2084_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_DOLBYVISION_EXT, VK_COLOR_SPACE_DOLBYVISION_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_HDR10_HLG_EXT, VK_COLOR_SPACE_HDR10_HLG_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_ADOBERGB_LINEAR_EXT, VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT, VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_PASS_THROUGH_EXT, VK_COLOR_SPACE_PASS_THROUGH_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT, VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT},
    {RHIColorSpace::RHI_COLOR_SPACE_DISPLAY_NATIVE_AMD, VK_COLOR_SPACE_DISPLAY_NATIVE_AMD},
};
    
Map<VkColorSpaceKHR, RHIColorSpace> createVkToRhiColorMap()
{
    Map<VkColorSpaceKHR, RHIColorSpace> map;
    for (const auto& pair : gk_colorSpaceMap) {
        map[pair.second] = pair.first;
    }
    return map;
}

} // anonymous namespace

VkImageLayout toVkImageLayout(RHIImageLayout layout) {
    auto it = gk_rhiToVkImageLayout.find(layout);
    if (it != gk_rhiToVkImageLayout.end())
        return it->second;
    return VK_IMAGE_LAYOUT_UNDEFINED;
}

RHIImageLayout toRhiImageLayout(VkImageLayout layout) {
    auto it = gk_vkToRhiImageLayout.find(layout);
    if (it != gk_vkToRhiImageLayout.end())
        return it->second;
    return RHIImageLayout::Undefined;
}

const Map<VkDescriptorType, RHIDescriptorType> gk_vkToRhiDescriptorType = createVkToRhiDescriptorTypeMap();
VkDescriptorType toVkDescriptorType(RHIDescriptorType type) {
    auto it = gk_rhiToVkDescriptorType.find(type);
    if (it != gk_rhiToVkDescriptorType.end())
        return it->second;
    return VK_DESCRIPTOR_TYPE_MAX_ENUM;
}

RHIDescriptorType toRhiDescriptorType(VkDescriptorType type) {
    auto it = gk_vkToRhiDescriptorType.find(type);
    if (it != gk_vkToRhiDescriptorType.end())
        return it->second;
    return RHIDescriptorType::UniformBuffer; // fallback, or consider an Invalid value
}

VkFormat toVkFormat(RHIFormat fmt)
{
    auto it = gk_rhiToVkFormat.find(fmt);
    if (it != gk_rhiToVkFormat.end()) {
        return it->second;
    }
    return VK_FORMAT_UNDEFINED;
}

RHIFormat toRhiFormat(VkFormat fmt)
{
    auto it = gk_vkToRhiFormat.find(fmt);
    if (it != gk_vkToRhiFormat.end()) {
        return it->second;
    }
    return RHIFormat::RHI_FORMAT_UNDEFINED;
}

VkColorSpaceKHR toVkColorSpace(RHIColorSpace cs)
{
    auto it = gk_colorSpaceMap.find(cs);
    if (it != gk_colorSpaceMap.end()) {
        return it->second;
    }
    return VK_COLOR_SPACE_SRGB_NONLINEAR_KHR;
}

RHIColorSpace toRhiColorSpace(VkColorSpaceKHR cs)
{
    auto it = createVkToRhiColorMap().find(cs);
    if (it != createVkToRhiColorMap().end()) {
        return it->second;
    }
    return RHIColorSpace::RHI_COLOR_SPACE_SRGB_NONLINEAR_KHR;
}

VkSurfaceFormatKHR toVkSurfaceFormat(const RHISurfaceFormat &fmt)
{
    VkSurfaceFormatKHR vkfmt{};
    vkfmt.format = toVkFormat(fmt.format);
    vkfmt.colorSpace = toVkColorSpace(fmt.color_space);
    return vkfmt;
}

RHISurfaceFormat toRhiSurfaceFormat(const VkSurfaceFormatKHR &vkfmt)
{
    RHISurfaceFormat fmt{};
    fmt.format = toRhiFormat(vkfmt.format);
    fmt.color_space = toRhiColorSpace(vkfmt.colorSpace);
    return fmt;
}

// --- Flag conversion implementations ---
namespace {
const Map<rhi::RHIBufferUsage, VkBufferUsageFlagBits> gk_rhiToVkBufferUsageBit = {
    {rhi::RHIBufferUsage::TransferSrc, VK_BUFFER_USAGE_TRANSFER_SRC_BIT},
    {rhi::RHIBufferUsage::TransferDst, VK_BUFFER_USAGE_TRANSFER_DST_BIT},
    {rhi::RHIBufferUsage::UniformTexelBuffer, VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT},
    {rhi::RHIBufferUsage::StorageTexelBuffer, VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT},
    {rhi::RHIBufferUsage::UniformBuffer, VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT},
    {rhi::RHIBufferUsage::StorageBuffer, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT},
    {rhi::RHIBufferUsage::IndexBuffer, VK_BUFFER_USAGE_INDEX_BUFFER_BIT},
    {rhi::RHIBufferUsage::VertexBuffer, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT},
    {rhi::RHIBufferUsage::IndirectBuffer, VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT},
    {rhi::RHIBufferUsage::ShaderDeviceAddress, VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT},
    {rhi::RHIBufferUsage::VideoDecodeSrc, VK_BUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHR},
    {rhi::RHIBufferUsage::VideoDecodeDst, VK_BUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHR},
    {rhi::RHIBufferUsage::TransformFeedbackBuffer, VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT},
    {rhi::RHIBufferUsage::TransformFeedbackCounterBuffer, VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT},
    {rhi::RHIBufferUsage::ConditionalRendering, VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT},
    {rhi::RHIBufferUsage::AccelerationStructureBuildInputReadOnly, VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR},
    {rhi::RHIBufferUsage::AccelerationStructureStorage, VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR},
    {rhi::RHIBufferUsage::ShaderBindingTable, VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR},
    {rhi::RHIBufferUsage::VideoEncodeDst, VK_BUFFER_USAGE_VIDEO_ENCODE_DST_BIT_KHR},
    {rhi::RHIBufferUsage::VideoEncodeSrc, VK_BUFFER_USAGE_VIDEO_ENCODE_SRC_BIT_KHR},
    {rhi::RHIBufferUsage::SamplerDescriptorBuffer, VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT},
    {rhi::RHIBufferUsage::ResourceDescriptorBuffer, VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT},
    {rhi::RHIBufferUsage::PushDescriptorsDescriptorBuffer, VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT},
    {rhi::RHIBufferUsage::MicromapBuildInputReadOnly, VK_BUFFER_USAGE_MICROMAP_BUILD_INPUT_READ_ONLY_BIT_EXT},
    {rhi::RHIBufferUsage::MicromapStorage, VK_BUFFER_USAGE_MICROMAP_STORAGE_BIT_EXT},
    {rhi::RHIBufferUsage::TileMemoryQCOM, VK_BUFFER_USAGE_TILE_MEMORY_QCOM},
};

const Map<rhi::RHIImageUsage, VkImageUsageFlagBits> gk_rhiToVkImageUsageBit = {
    {rhi::RHIImageUsage::TransferSrc,            VK_IMAGE_USAGE_TRANSFER_SRC_BIT},
    {rhi::RHIImageUsage::TransferDst,            VK_IMAGE_USAGE_TRANSFER_DST_BIT},
    {rhi::RHIImageUsage::Sampled,                VK_IMAGE_USAGE_SAMPLED_BIT},
    {rhi::RHIImageUsage::Storage,                VK_IMAGE_USAGE_STORAGE_BIT},
    {rhi::RHIImageUsage::ColorAttachment,        VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT},
    {rhi::RHIImageUsage::DepthStencilAttachment, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT},
};

const Map<rhi::RHIMemoryProperty, VkMemoryPropertyFlagBits> gk_rhiToVkMemoryPropertyBit = {
    {rhi::RHIMemoryProperty::DeviceLocal,  VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT},
    {rhi::RHIMemoryProperty::HostVisible,  VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT},
    {rhi::RHIMemoryProperty::HostCoherent, VK_MEMORY_PROPERTY_HOST_COHERENT_BIT},
};

const Map<rhi::RHIShaderStage, VkShaderStageFlagBits> gk_rhiToVkShaderStageBit = {
    {rhi::RHIShaderStage::Vertex, VK_SHADER_STAGE_VERTEX_BIT},
    {rhi::RHIShaderStage::TessellationControl, VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT},
    {rhi::RHIShaderStage::TessellationEvaluation, VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT},
    {rhi::RHIShaderStage::Geometry, VK_SHADER_STAGE_GEOMETRY_BIT},
    {rhi::RHIShaderStage::Fragment, VK_SHADER_STAGE_FRAGMENT_BIT},
    {rhi::RHIShaderStage::Compute, VK_SHADER_STAGE_COMPUTE_BIT},
    {rhi::RHIShaderStage::RayGen, VK_SHADER_STAGE_RAYGEN_BIT_KHR},
    {rhi::RHIShaderStage::AnyHit, VK_SHADER_STAGE_ANY_HIT_BIT_KHR},
    {rhi::RHIShaderStage::ClosestHit, VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR},
    {rhi::RHIShaderStage::Miss, VK_SHADER_STAGE_MISS_BIT_KHR},
    {rhi::RHIShaderStage::Intersection, VK_SHADER_STAGE_INTERSECTION_BIT_KHR},
    {rhi::RHIShaderStage::Callable, VK_SHADER_STAGE_CALLABLE_BIT_KHR},
    {rhi::RHIShaderStage::Task, VK_SHADER_STAGE_TASK_BIT_EXT},
    {rhi::RHIShaderStage::Mesh, VK_SHADER_STAGE_MESH_BIT_EXT},
    {rhi::RHIShaderStage::SubpassShadingHuawei, VK_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI},
    {rhi::RHIShaderStage::ClusterCullingHuawei, VK_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI},
};
} // anonymous namespace

VkBufferUsageFlags toVkBufferUsageFlags(rhi::RHIBufferUsageFlags flags) {
    VkBufferUsageFlags result = 0;
    for (const auto& [rhiBit, vkBit] : gk_rhiToVkBufferUsageBit) {
        if (flags.test(rhiBit)) {
            result |= vkBit;
        }
    }
    return result;
}

RHIBufferUsageFlags toRhiBufferUsageFlags(VkBufferUsageFlags flags) {
    rhi::RHIBufferUsageFlags result;
    for (const auto& [rhiBit, vkBit] : gk_rhiToVkBufferUsageBit) {
        if (flags & vkBit) {
            result |= rhiBit;
        }
    }
    return result;
}

VkImageUsageFlags toVkImageUsageFlags(rhi::RHIImageUsageFlags flags) {
    VkImageUsageFlags result = 0;
    for (const auto& [rhiBit, vkBit] : gk_rhiToVkImageUsageBit) {
        if (flags.test(rhiBit)) {
            result |= vkBit;
        }
    }
    return result;
}

RHIImageUsageFlags toRhiImageUsageFlags(VkImageUsageFlags flags) {
    rhi::RHIImageUsageFlags result;
    for (const auto& [rhiBit, vkBit] : gk_rhiToVkImageUsageBit) {
        if (flags & vkBit) {
            result |= rhiBit;
        }
    }
    return result;
}

VkMemoryPropertyFlags toVkMemoryPropertyFlags(rhi::RHIMemoryPropertyFlags flags) {
    VkMemoryPropertyFlags result = 0;
    for (const auto& [rhiBit, vkBit] : gk_rhiToVkMemoryPropertyBit) {
        if (flags.test(rhiBit)) {
            result |= vkBit;
        }
    }
    return result;
}

RHIMemoryPropertyFlags toRhiMemoryPropertyFlags(VkMemoryPropertyFlags flags) {
    rhi::RHIMemoryPropertyFlags result;
    for (const auto& [rhiBit, vkBit] : gk_rhiToVkMemoryPropertyBit) {
        if (flags & vkBit) {
            result |= rhiBit;
        }
    }
    return result;
}

VkShaderStageFlags toVkShaderStageFlags(rhi::RHIShaderStageFlags flags) {
    VkShaderStageFlags result = 0;
    for (const auto& [rhiBit, vkBit] : gk_rhiToVkShaderStageBit) {
        if (flags.test(rhiBit)) {
            result |= vkBit;
        }
    }
    return result;
}

RHIShaderStageFlags toRhiShaderStageFlags(VkShaderStageFlags flags) {
    rhi::RHIShaderStageFlags result;
    for (const auto& [rhiBit, vkBit] : gk_rhiToVkShaderStageBit) {
        if (flags & vkBit) {
            result |= rhiBit;
        }
    }
    return result;
}

} // namespace rhi::vulkan